### ISSUE TITLE
The readme demos are broken

### ISSUE THREAD

**Issue by mo6zes** [mariosasko/datasets_sql#1]
I tried running an example from the repo but the code is broken:

```
imdb_dset = load_dataset("imdb", split="train")
dataset = query(
    "SELECT text FROM imdb_dset"
)
```
results in
`AttributeError: 'duckdb.DuckDBPyConnection' object has no attribute 'fetch_arrow_chunk'`

I am using datasets_sql version 0.1.1 and datasets version 2.5.2

**Comment by mariosasko** [comment]
Hi, thanks for reporting! I've just publised a new release of the package that fixes this issue.
