### ISSUE TITLE
How to use query function if dataset is a class attribute

### ISSUE THREAD

**Issue by freddyaboulton** [mariosasko/datasets_sql#2]
Awesome library!

This is probably a generic duckdb question but figured I'd ask here first. If I store a reference to a dataset in a class attribute, how do I get `query` to find my dataset?

Repro:

```python
class DatasetQuery:
    
    def __init__(self, dataset_name, split="train"):
        ds = datasets.load_dataset(dataset_name, split="train")
        self.dataset = ds
    
    def query(self, query_str):
        return query(query_str)

dq = DatasetQuery("huggingnft/boredapeyachtclub")
dq.query("select * from ?? limit 10;")
```

What do I put in the from clause? I tried `ds` and `self.dataset` but neither work. I get `ValueError: The dataset `ds` not found in the namespace.`

**Comment by mariosasko** [comment]
`ds` works if the query function is defined as follows:
```python
def query(self, query_str):
        ds = self.dataset
        return query(query_str) # <- this is where the namespace traversal starts
```

And for the `self.dataset` to work, we would have to extend the replacement scan to support the "dot" syntax, which should be easy to implement.

**Comment by mariosasko** [comment]
> And for the self.dataset to work, we would have to extend the replacement scan to support the "dot" syntax, which should be easy to implement.

This is now fixed on `main` (use `pip install git+https://github.com/mariosasko/datasets_sql.git` to download it). I'll publish a new release in a few weeks.

**Comment by freddyaboulton** [comment]
Will close this issue then @mariosasko ! Thank you for the fix. Any reason to hold up the release?

**Comment by mariosasko** [comment]
The new release has been published :).

**Comment by mariosasko** [comment]
> This is now fixed on main (use pip install git+https://github.com/mariosasko/datasets_sql.git to download it). I'll publish a new release in a few weeks.

I've decided to revert this feature in the latest release, as it would require manually extracting table names in the newer DuckDB versions. DuckDB replacement scans do not support this syntax anyway, so I think this change is reasonable.
